services:
  postgres:
    image: 'postgres:16.6'
    container_name: name
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata: