-- Create tables
CREATE TABLE "core"."users"
    (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "first_name" text, "last_name" text,
        "date_of_birth" date, "pending_email" text,
        "email" text, "pending_phone_number" text,
        "phone_number" text,
        "deleted_at" TIMESTAMP WITH TIME ZONE,
        "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "registration_status" text NOT NULL DEFAULT 'notRegistered',
        "onboard_status" text,
        "address_line1" text,
        "address_line2" text,
        "city" text,
        "state" text,
        "zip_code" text,
        "verification_type" text,
        "secret" text,
        "secret_expires_at" TIMESTAMP WITH TIME ZONE,
        "verification_status" text NOT NULL DEFAULT 'notVerified',
        "verification_attempts" integer NOT NULL DEFAULT '0',
        "verification_locked_until" TIMESTAMP WITH TIME ZONE,
        CONSTRAINT "users_email_key" UNIQUE ("email"),
        CONSTRAINT "users_phone_number_key" UNIQUE ("phone_number"),
        CONSTRAINT "core.users_id_pkey" PRIMARY KEY ("id")
    );
CREATE TABLE "core"."biller_addresses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "biller_id" uuid NOT NULL, "external_key" text NOT NULL, "live_date" date NOT NULL, "address_line1" text NOT NULL, "address_line2" text, "city" text NOT NULL, "state_province_code" text NOT NULL, "country_code" text NOT NULL, "postal_code" text NOT NULL, CONSTRAINT "core.biller_addresses_id_pkey" PRIMARY KEY ("id"));
CREATE TABLE "core"."biller_masks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "biller_id" uuid NOT NULL, "mask" text NOT NULL, "mask_length" integer NOT NULL, "external_key" text NOT NULL, "live_date" date NOT NULL, CONSTRAINT "core.biller_masks_id_pkey" PRIMARY KEY ("id"));
CREATE TABLE "core"."biller_names" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "biller_id" uuid NOT NULL, "name" text NOT NULL, "external_key" text NOT NULL, "live_date" date NOT NULL, CONSTRAINT "core.biller_names_id_pkey" PRIMARY KEY ("id"));
CREATE INDEX "biller_names_name_idx" ON "core"."biller_names" ("name") ;
CREATE TABLE "core"."payment_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "type" text NOT NULL, "provider" text NOT NULL, "ownership" text NOT NULL, "state" text NOT NULL, "details" jsonb, "owner_id" uuid, CONSTRAINT "core.payment_accounts_id_pkey" PRIMARY KEY ("id"));
CREATE TABLE "core"."billers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "type" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "created_by_id" uuid, "payment_account_id" uuid, "external_biller_id" text, "external_biller_key" text, "live_date" date NOT NULL, "biller_class" text, "biller_type" text, "line_of_business" text, "territory_code" text, "crc32" bigint NOT NULL, CONSTRAINT "core.billers_id_pkey" PRIMARY KEY ("id"));
CREATE TABLE "core"."loan_applications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" text DEFAULT 'pending', "loan_id" uuid, "biller_id" uuid, "biller_name" text, "biller_postal_code" text, "biller_class" text, "bill_account_number" text, "lender_id" uuid, "lender_payment_account_id" uuid, "lender_first_name" text, "lender_last_name" text, "lender_email" text, "lender_relationship" text, "lender_note" text, "lender_responded_at" TIMESTAMP WITH TIME ZONE, "borrower_id" uuid, "borrower_first_name" text, "borrower_last_name" text, "borrower_payment_account_id" uuid, "borrower_submitted_at" TIMESTAMP WITH TIME ZONE, "loan_type" text DEFAULT 'dbp', "loan_payment_frequency" text DEFAULT 'monthly', "loan_amount" numeric(12,2), "loan_payments" integer DEFAULT '3', "loan_service_fee" numeric(12,4) DEFAULT '0', "loan_first_payment_date" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "borrower_account_id" uuid, CONSTRAINT "loan_applications_loan_id_key" UNIQUE ("loan_id"), CONSTRAINT "core.loan_applications_id_pkey" PRIMARY KEY ("id"));
CREATE TABLE "core"."loans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "amount" numeric NOT NULL, "lender_id" uuid, "borrower_id" uuid, "type" text NOT NULL, "state" text NOT NULL, "closure_type" text NOT NULL DEFAULT 'open', "relationship" text, "reason" text, "note" text, "attachment" text, "deeplink" text, "biller_id" uuid, "billing_account_number" text, "payments_count" integer NOT NULL, "payment_frequency" text NOT NULL, "fee_mode" text, "fee_amount" numeric NOT NULL DEFAULT '0', "principal_amount_left" numeric NOT NULL DEFAULT '0', "fee_amount_left" numeric NOT NULL DEFAULT '0', "lender_account_id" uuid, "borrower_account_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "accepted_at" TIMESTAMP WITH TIME ZONE, "retry_count" integer NOT NULL DEFAULT '0', CONSTRAINT "loans_borrower_id_ne_lender_id_check" CHECK ("borrower_id" <> "lender_id"), CONSTRAINT "core.loans_id_pkey" PRIMARY KEY ("id"));
CREATE TABLE "payments"."transfer_errors" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "transfer_id" uuid NOT NULL, "loan_id" uuid, "type" text NOT NULL, "code" text NOT NULL, "display_message" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "raw" text NOT NULL, CONSTRAINT "REL_c484fc714d2e3f85aab35a4147" UNIQUE ("transfer_id"), CONSTRAINT "payments.transfer_errors_id_pkey" PRIMARY KEY ("id"));
CREATE TABLE "payments"."transfers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "amount" numeric NOT NULL, "state" text NOT NULL, "error_data" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "source_account_id" uuid NOT NULL, "destination_account_id" uuid NOT NULL, "order" integer NOT NULL DEFAULT '0', "loan_payment_step_id" uuid, CONSTRAINT "payments.transfers_id_pkey" PRIMARY KEY ("id"));
CREATE TABLE "payments"."loan_payment_steps" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "loan_payment_id" uuid NOT NULL, "order" integer NOT NULL DEFAULT '0', "amount" numeric NOT NULL, "source_payment_account_id" uuid NOT NULL, "target_payment_account_id" uuid NOT NULL, "state" text NOT NULL, "await_step_state" text, "await_step_id" uuid, CONSTRAINT "payments.loan_payment_steps_id_pkey" PRIMARY KEY ("id"));
CREATE TABLE "payments"."loan_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "amount" numeric NOT NULL, "fee_amount" numeric NOT NULL DEFAULT '0', "loan_id" uuid NOT NULL, "payment_number" integer, "type" text NOT NULL, "attempt" integer NOT NULL DEFAULT '0', "state" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "initiated_at" TIMESTAMP WITH TIME ZONE, "scheduled_at" TIMESTAMP WITH TIME ZONE, "completed_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "payments.loan_payments_id_pkey" PRIMARY KEY ("id"));
CREATE TABLE "payments"."loan_payments_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "loan_payment_id" uuid NOT NULL, "from_state" text, "to_state" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "payments.loan_payments_history_id_pkey" PRIMARY KEY ("id"));
CREATE TABLE "core"."user_logins" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "login_type" text NOT NULL, "secret" text, "secret_expires_at" TIMESTAMP WITH TIME ZONE, "session_id" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), CONSTRAINT "core.user_logins_id_pkey" PRIMARY KEY ("id"));
CREATE TABLE "notifications"."notification_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "target" text NOT NULL, "status" text NOT NULL, "user_id" uuid NOT NULL, "transport" text NOT NULL, "metadata" text NOT NULL DEFAULT '', "header" text NOT NULL DEFAULT '', "body" text NOT NULL DEFAULT '', "message" text NOT NULL DEFAULT '', "definition_item_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "notifications.notification_logs_id_pkey" PRIMARY KEY ("id"));
CREATE TYPE "notifications"."notification_definition_items_notification_type_enum" AS ENUM('email', 'sms', 'amplitude');
CREATE TABLE "notifications"."notification_definition_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "notification_definition_id" uuid NOT NULL, "order_index" integer NOT NULL, "notification_type" "notifications"."notification_definition_items_notification_type_enum" NOT NULL, "template" text, "header" text, "body" text, "target" text, "metadata" text, "attributes" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "notifications.notification_definition_items_id_pkey" PRIMARY KEY ("id"));
CREATE TABLE "notifications"."notification_definitions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "data_items" jsonb NOT NULL DEFAULT '["user"]', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "notifications.notification_definitions_id_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "notification_definitions_name_idx" ON "notifications"."notification_definitions" ("name") ;
CREATE TABLE "payments"."payments_route_steps" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "route_id" uuid NOT NULL, "order" integer NOT NULL DEFAULT '0', "from_id" uuid, "to_id" uuid, CONSTRAINT "payments.payments_route_steps_id_pkey" PRIMARY KEY ("id"));
CREATE TABLE "payments"."payments_routes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "from_account" text NOT NULL, "from_ownership" text NOT NULL, "from_provider" text NOT NULL, "to_account" text NOT NULL, "to_ownership" text NOT NULL, "to_provider" text NOT NULL, "loan_stages_supported" text array NOT NULL, "loan_types_supported" text array NOT NULL, CONSTRAINT "payments.payments_routes_id_pkey" PRIMARY KEY ("id"));
CREATE TABLE "core"."user_registrations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "status" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "secret" text, "secret_expires_at" TIMESTAMP WITH TIME ZONE, "user_login_id" uuid, CONSTRAINT "REL_2843251e5fda06bf0d3f3b6149" UNIQUE ("user_id"), CONSTRAINT "core.user_registrations_id_pkey" PRIMARY KEY ("id"));
CREATE INDEX "user_registrations_user_id_idx" ON "core"."user_registrations" ("user_id") ;
CREATE INDEX "user_registrations_user_login_id_idx" ON "core"."user_registrations" ("user_login_id") ;

-- Update tebles
ALTER TABLE "core"."payment_accounts" ADD CONSTRAINT "payment_accounts_owner_id_users_fkey" FOREIGN KEY ("owner_id") REFERENCES "core"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "core"."billers" ADD CONSTRAINT "billers_created_by_id_users_fkey" FOREIGN KEY ("created_by_id") REFERENCES "core"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "core"."billers" ADD CONSTRAINT "billers_payment_account_id_payment_accounts_fkey" FOREIGN KEY ("payment_account_id") REFERENCES "core"."payment_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "core"."loan_applications" ADD CONSTRAINT "loan_applications_biller_id_billers_fkey" FOREIGN KEY ("biller_id") REFERENCES "core"."billers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "core"."loan_applications" ADD CONSTRAINT "loan_applications_lender_id_users_fkey" FOREIGN KEY ("lender_id") REFERENCES "core"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "core"."loan_applications" ADD CONSTRAINT "loan_applications_lender_payment_account_id_payment_accounts_fk" FOREIGN KEY ("lender_payment_account_id") REFERENCES "core"."payment_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "core"."loan_applications" ADD CONSTRAINT "loan_applications_borrower_id_users_fkey" FOREIGN KEY ("borrower_id") REFERENCES "core"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "core"."loan_applications" ADD CONSTRAINT "loan_applications_borrower_account_id_payment_accounts_fkey" FOREIGN KEY ("borrower_account_id") REFERENCES "core"."payment_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "core"."loans" ADD CONSTRAINT "loans_lender_id_users_fkey" FOREIGN KEY ("lender_id") REFERENCES "core"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "core"."loans" ADD CONSTRAINT "loans_borrower_id_users_fkey" FOREIGN KEY ("borrower_id") REFERENCES "core"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "core"."loans" ADD CONSTRAINT "loans_biller_id_billers_fkey" FOREIGN KEY ("biller_id") REFERENCES "core"."billers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "core"."loans" ADD CONSTRAINT "loans_lender_account_id_payment_accounts_fkey" FOREIGN KEY ("lender_account_id") REFERENCES "core"."payment_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "core"."loans" ADD CONSTRAINT "loans_borrower_account_id_payment_accounts_fkey" FOREIGN KEY ("borrower_account_id") REFERENCES "core"."payment_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "payments"."transfer_errors" ADD CONSTRAINT "transfer_errors_transfer_id_transfers_fkey" FOREIGN KEY ("transfer_id") REFERENCES "payments"."transfers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "payments"."transfer_errors" ADD CONSTRAINT "transfer_errors_loan_id_loans_fkey" FOREIGN KEY ("loan_id") REFERENCES "core"."loans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "payments"."transfers" ADD CONSTRAINT "transfers_source_account_id_payment_accounts_fkey" FOREIGN KEY ("source_account_id") REFERENCES "core"."payment_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "payments"."transfers" ADD CONSTRAINT "transfers_destination_account_id_payment_accounts_fkey" FOREIGN KEY ("destination_account_id") REFERENCES "core"."payment_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "payments"."transfers" ADD CONSTRAINT "transfers_loan_payment_step_id_loan_payment_steps_fkey" FOREIGN KEY ("loan_payment_step_id") REFERENCES "payments"."loan_payment_steps"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "payments"."loan_payment_steps" ADD CONSTRAINT "loan_payment_steps_loan_payment_id_loan_payments_fkey" FOREIGN KEY ("loan_payment_id") REFERENCES "payments"."loan_payments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "payments"."loan_payment_steps" ADD CONSTRAINT "loan_payment_steps_source_payment_account_id_payment_accounts_f" FOREIGN KEY ("source_payment_account_id") REFERENCES "core"."payment_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "payments"."loan_payment_steps" ADD CONSTRAINT "loan_payment_steps_target_payment_account_id_payment_accounts_f" FOREIGN KEY ("target_payment_account_id") REFERENCES "core"."payment_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "payments"."loan_payments" ADD CONSTRAINT "loan_payments_loan_id_loans_fkey" FOREIGN KEY ("loan_id") REFERENCES "core"."loans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "payments"."loan_payments_history" ADD CONSTRAINT "loan_payments_history_loan_payment_id_loan_payments_fkey" FOREIGN KEY ("loan_payment_id") REFERENCES "payments"."loan_payments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "core"."user_logins" ADD CONSTRAINT "user_logins_user_id_users_fkey" FOREIGN KEY ("user_id") REFERENCES "core"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "notifications"."notification_logs" ADD CONSTRAINT "notification_logs_definition_item_id_notification_definition_it" FOREIGN KEY ("definition_item_id") REFERENCES "notifications"."notification_definition_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "notifications"."notification_definition_items" ADD CONSTRAINT "notification_definition_items_notification_definition_id_notifi" FOREIGN KEY ("notification_definition_id") REFERENCES "notifications"."notification_definitions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "payments"."payments_route_steps" ADD CONSTRAINT "payments_route_steps_route_id_payments_routes_fkey" FOREIGN KEY ("route_id") REFERENCES "payments"."payments_routes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "payments"."payments_route_steps" ADD CONSTRAINT "payments_route_steps_from_id_payment_accounts_fkey" FOREIGN KEY ("from_id") REFERENCES "core"."payment_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "payments"."payments_route_steps" ADD CONSTRAINT "payments_route_steps_to_id_payment_accounts_fkey" FOREIGN KEY ("to_id") REFERENCES "core"."payment_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "core"."user_registrations" ADD CONSTRAINT "user_registrations_user_id_users_fkey" FOREIGN KEY ("user_id") REFERENCES "core"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION;
