ALTER TABLE "core"."user_registrations" DROP CONSTRAINT "user_registrations_user_id_users_fkey";
ALTER TABLE "payments"."payments_route_steps" DROP CONSTRAINT "payments_route_steps_to_id_payment_accounts_fkey";
ALTER TABLE "payments"."payments_route_steps" DROP CONSTRAINT "payments_route_steps_from_id_payment_accounts_fkey";
ALTER TABLE "payments"."payments_route_steps" DROP CONSTRAINT "payments_route_steps_route_id_payments_routes_fkey";
ALTER TABLE "notifications"."notification_definition_items" DROP CONSTRAINT "notification_definition_items_notification_definition_id_notifi";
ALTER TABLE "notifications"."notification_logs" DROP CONSTRAINT "notification_logs_definition_item_id_notification_definition_it";
ALTER TABLE "core"."user_logins" DROP CONSTRAINT "user_logins_user_id_users_fkey";
ALTER TABLE "payments"."loan_payments_history" DROP CONSTRAINT "loan_payments_history_loan_payment_id_loan_payments_fkey";
ALTER TABLE "payments"."loan_payments" DROP CONSTRAINT "loan_payments_loan_id_loans_fkey";
ALTER TABLE "payments"."loan_payment_steps" DROP CONSTRAINT "loan_payment_steps_target_payment_account_id_payment_accounts_f";
ALTER TABLE "payments"."loan_payment_steps" DROP CONSTRAINT "loan_payment_steps_source_payment_account_id_payment_accounts_f";
ALTER TABLE "payments"."loan_payment_steps" DROP CONSTRAINT "loan_payment_steps_loan_payment_id_loan_payments_fkey";
ALTER TABLE "payments"."transfers" DROP CONSTRAINT "transfers_loan_payment_step_id_loan_payment_steps_fkey";
ALTER TABLE "payments"."transfers" DROP CONSTRAINT "transfers_destination_account_id_payment_accounts_fkey";
ALTER TABLE "payments"."transfers" DROP CONSTRAINT "transfers_source_account_id_payment_accounts_fkey";
ALTER TABLE "payments"."transfer_errors" DROP CONSTRAINT "transfer_errors_loan_id_loans_fkey";
ALTER TABLE "payments"."transfer_errors" DROP CONSTRAINT "transfer_errors_transfer_id_transfers_fkey";
ALTER TABLE "core"."loans" DROP CONSTRAINT "loans_borrower_account_id_payment_accounts_fkey";
ALTER TABLE "core"."loans" DROP CONSTRAINT "loans_lender_account_id_payment_accounts_fkey";
ALTER TABLE "core"."loans" DROP CONSTRAINT "loans_biller_id_billers_fkey";
ALTER TABLE "core"."loans" DROP CONSTRAINT "loans_borrower_id_users_fkey";
ALTER TABLE "core"."loans" DROP CONSTRAINT "loans_lender_id_users_fkey";
ALTER TABLE "core"."loan_applications" DROP CONSTRAINT "loan_applications_borrower_account_id_payment_accounts_fkey";
ALTER TABLE "core"."loan_applications" DROP CONSTRAINT "loan_applications_borrower_id_users_fkey";
ALTER TABLE "core"."loan_applications" DROP CONSTRAINT "loan_applications_lender_payment_account_id_payment_accounts_fk";
ALTER TABLE "core"."loan_applications" DROP CONSTRAINT "loan_applications_lender_id_users_fkey";
ALTER TABLE "core"."loan_applications" DROP CONSTRAINT "loan_applications_biller_id_billers_fkey";
ALTER TABLE "core"."billers" DROP CONSTRAINT "billers_payment_account_id_payment_accounts_fkey";
ALTER TABLE "core"."billers" DROP CONSTRAINT "billers_created_by_id_users_fkey";
ALTER TABLE "core"."payment_accounts" DROP CONSTRAINT "payment_accounts_owner_id_users_fkey";
DROP INDEX "core"."user_registrations_user_login_id_idx";
DROP INDEX "core"."user_registrations_user_id_idx";
DROP TABLE "core"."user_registrations";
DROP TABLE "payments"."payments_routes";
DROP TABLE "payments"."payments_route_steps";
DROP INDEX "notifications"."notification_definitions_name_idx";
DROP TABLE "notifications"."notification_definitions";
DROP TABLE "notifications"."notification_definition_items";
DROP TYPE "notifications"."notification_definition_items_notification_type_enum";
DROP TABLE "notifications"."notification_logs";
DROP TABLE "core"."user_logins";
DROP TABLE "payments"."loan_payments_history";
DROP TABLE "payments"."loan_payments";
DROP TABLE "payments"."loan_payment_steps";
DROP TABLE "payments"."transfers";
DROP TABLE "payments"."transfer_errors";
DROP TABLE "core"."loans";
DROP TABLE "core"."loan_applications";
DROP TABLE "core"."billers";
DROP TABLE "core"."payment_accounts";
DROP INDEX "core"."biller_names_name_idx";
DROP TABLE "core"."biller_names";
DROP TABLE "core"."biller_masks";
DROP TABLE "core"."biller_addresses";
DROP TABLE "core"."users";
