export enum DomainExceptionCode {
  Undefined = 'undefined',
  EntityNotFound = 'entity_not_found',
  UnauthorizedRequest = 'unauthorized_request',
  MissingInput = 'missing_input',
  UserNotRegistered = 'user_not_registered',
  LoginSessionNotInitiated = 'login_session_not_initiated',
  LoginSessionExpired = 'login_session_expired',
  VerificationCodeMismatch = 'verification_code_mismatch',
  UnableToGenerateLoginPayload = 'unable_to_generate_login_payload',
  UnexpectedRegistrationStatus = 'unexpected_registration_status',
  ConfigurationVariableNotFound = 'configuration_variable_not_found',
  RegistrationSessionNotInitiated = 'registration_session_not_initiated',
  RegistrationSessionNotWaitingForVerification = 'registration_session_not_waiting_for_verification',
  RegistrationSecretNotFound = 'registration_secret_not_found',
  RegistrationSecretExpired = 'registration_secret_expired',
  UnableToCreateLoginOnRegistration = 'unable_to_create_login_on_registration',
  ContactTaken = 'contact_taken',
  UnableToCreateUser = 'unable_to_create_user',  
  RegistrationNotFound = 'registration_not_found',
  RegistrationProcessingFailed = 'registration_processing_failed',
  WrongVerificationType = 'wrong_verification_type',
}
